CREATE TABLE dimensions(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  "length" BIGINT NOT NULL,
  assignment VARCHAR(255) NOT NULL,
  resolution DOUBLE PRECISION,
  unit VARCHAR(255),
  package_id INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER dimensions_update_updated_at BEFORE UPDATE ON dimensions FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
